---
title: "Week 4, Day 1"
date: "9/27/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library(janitor)
```

Let's continue working with enrollment data. I have downloaded 5 years of fall enrollment data in to the `raw_data` directory from the [official source](https://registrar.fas.harvard.edu/faculty-staff/courses/enrollment/archived-course-enrollment-reports).

### Scene 1

**Prompt:** Write a pipe which creates an object named `d_2019` by reading in and cleaning up the data from fall 2019. (You will need to examine the file names to determine which file this is.) You may consult and re-use the code from last week. The variable names in the tibble should be `id`,  `title`, `name`, `department` and `u_grad`. Keep only classes with more than 10 undergrads enrolled.

**Answer:** 

### Scene 2

**Prompt:** We could copy/paste this code 5 times, adjust the files names, and then read in each file. But, as you know from Chapter 4, that is a bad idea. It also scales very poorly. Create a function called `read_enrollent` which takes one argument, `file`. Use that function to read in the data from fall 2019 and assign it to an object called `d_2019_take_2`. Do you get the same answer as you did in Scene 1?

**Answer:** 

### Scene 3

**Prompt:** Call `read_enrollent()` five times, once for each of our data sets. Note how different the file names are. Read data is messy! Assign the result of each call to an object, `d_2019`, `d_2018` and so on. Should be easy . . .
Arrg! Depending in how you wrote `read_enrollment()`, you will probably be getting an error. How annoying the Harvard changes the format! Make your function flexible enough to deal with all these files. Hint: You need to add at least one argument in addition to `file` so that you can change hte behavior of the function when you call it. Give that new argument a sensible deafult.

**Answer:** 

### Scene 4

**Prompt:** Combine the five tibbles which you have into a single tibble which can then be used for analysis and graphics. There are many ways to do this, but we recommend `bind_rows()`. Hint: make use of the `.id` argument, which may be aided by placing the tibbles in a list.

### Scene 5

**Prompt:** Make an interesting plot with this data.
